incarnation: protelis

variables:
  n: &n
    type: GeometricVariable
    parameters: [400, 100, 1000, 5]
  seed: &seed
    min: 0
    max: 1
    step: 1
    default: 0
  gridWidthInM: &gridWidthInM
    formula: 2200 # estimated with GMAPS
  gridHeightInM: &gridHeightInM
    formula: 1000 # estimated with GMAPS
  neighborgInRange: &neighborgInRange
    formula: 10
  commRange: &commRange
    # with homogenous density: deviceNumber / mapArea = neighboringDevices / circleArea
    formula: Math.sqrt($gridHeightInM * $gridWidthInM * $neighborgInRange / ($n * Math.PI))

network-model:
  type: EuclideanDistance
  parameters: [*commRange]

environment: 
  type: OSMEnvironment
  parameters: [src/main/resources/cesena.pbf]

positions:
  type: LatLongPosition

pools:
  - pool: &distanceTo
    - time-distribution: 1
      program: distanceTo
    - time-distribution: null
      program: send

displacements:
  - in:
      type: Rectangle
      parameters: [*n, 44.1323, 12.233, 0.007959, 0.024449]
    programs: 
      - *distanceTo

export:
  - time
  - number-of-nodes
  - molecule: distance
#    aggregators: [mean]